name: Bump App version (after PR merge)

# Trigger on pull request creation, updates, and merges to main branch
on:
  push:
    branches:
      - main

jobs:
  # Build job for Pull Requests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install -g pnpm@9.10.0
          pnpm install

      - name: Run build script
        run: pnpm run build
        env:
          CI: true

  bump-version:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
          version-type: 'patch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json

      - name: Trigger Vercel redeploy
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
