name: Bump App Version and Deploy

on:
  push:
    branches:
      - main

jobs:
  bump-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          npm install -g pnpm@9.10.0
          pnpm install

      # 4️⃣ Run build
      - name: Build project
        run: pnpm run build
        env:
          CI: true

      # 5️⃣ Bump version
      - name: Bump version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
          version-type: 'patch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Optional: show updated package.json
      - name: Show package.json
        run: cat ./package.json

      # 7️⃣ Trigger Vercel redeploy
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" \
          -H "Content-Type: application/json"
